import httpClient from '../api/httpClient';
import { handleApiError } from '../api/errorHandler';
import type {
    DriverModel,
    AdminCreateDriverRequest,
    DriverCreatedResponse,
    DriverResponse,
    DriversResponse,
    DriverCreatedApiResponse
} from './types';

/**
 * Service for handling driver-related API calls
 */
const driverService = {
    /**
     * Get all drivers
     * @returns Promise with array of drivers
     */
    getAllDrivers: async (): Promise<DriverModel[]> => {
        try {
            const response = await httpClient.get<DriversResponse>('/drivers');
            return response.data.data;
        } catch (error) {
            console.error('Error fetching drivers:', error);
            throw handleApiError(error, 'Không thể tải danh sách tài xế');
        }
    },

    /**
     * Get driver by ID
     * @param id Driver ID
     * @returns Promise with driver data
     */
    getDriverById: async (id: string): Promise<DriverModel> => {
        try {
            const response = await httpClient.get<DriverResponse>(`/drivers/${id}`);
            return response.data.data;
        } catch (error) {
            console.error(`Error fetching driver ${id}:`, error);
            throw handleApiError(error, 'Không thể tải thông tin tài xế');
        }
    },

    /**
     * Update driver status
     * @param id Driver ID
     * @param status New status
     * @returns Promise with updated driver
     */
    updateDriverStatus: async (id: string, status: string): Promise<DriverModel> => {
        try {
            const response = await httpClient.patch<DriverResponse>(
                `/drivers/${id}/status`,
                null,
                { params: { status } }
            );
            return response.data.data;
        } catch (error) {
            console.error(`Error updating driver status ${id}:`, error);
            throw handleApiError(error, 'Không thể cập nhật trạng thái tài xế');
        }
    },

    /**
     * Validate driver eligibility by phone number for assignment
     * @param phoneNumber Driver phone number
     * @returns Promise with driver eligibility data
     */
    validateDriverByPhone: async (phoneNumber: string): Promise<DriverModel> => {
        try {
            const response = await httpClient.get<DriverResponse>(
                `/drivers/validate-by-phone/${phoneNumber}`
            );
            return response.data.data;
        } catch (error) {
            console.error(`Error validating driver with phone ${phoneNumber}:`, error);
            throw handleApiError(error, 'Không thể xác thực tài xế');
        }
    },

    /**
     * Create new driver (Admin only).
     * Password is auto-generated by backend.
     * Driver will be created with INACTIVE status and must complete onboarding on first login.
     * 
     * @param driverData Driver creation data (no password required)
     * @returns Promise with created driver info and temporary password
     */
    createDriver: async (driverData: AdminCreateDriverRequest): Promise<DriverCreatedResponse> => {
        try {
            const response = await httpClient.post<DriverCreatedApiResponse>(
                '/managers/driver/create',
                driverData
            );
            return response.data.data;
        } catch (error) {
            console.error('Error creating driver:', error);
            throw handleApiError(error, 'Không thể tạo tài xế');
        }
    }
};

export default driverService;